### ISSUE TITLE
Feature request to support ECS Service autoscaling

### ISSUE THREAD

**Issue by etsangsplk** [awslabs/aws-cloudformation-templates#10]
Request to support ECS Service autoscaling. Not many examples out there at this point. Most are about the same scenario. Nothing about more advanced use case to answer if Rolling upgrade possible within ECS service autoscaling.

**Comment by LRomandine** [comment]
Can you give me some more details for what you are requesting?  We have an example template in the [official documentation for ECS autoscaling.](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/quickref-ecs.html)

CloudFormation does not currently have the capability to easily perform a rolling upgrade of ECS.  It can update items such as the task definition but it can not perform a graceful rolling upgrade that adds # instances, tests them, adds them to the load balancer, drains connections off the old instances, etc.  It would likely be possible to perform what you are asking by using Lambda custom resources.

If you would like CloudFormation to support rolling updates to ECS like that you can put in a feature request using the support center in your AWS console.

**Comment by LRomandine** [comment]
Closing request due to 1 month inactivity.

**Comment by adamdude828** [comment]
I don't see the ability to autoscale the service. In the console I have the ability to add/remove containers based on load. I can write cloud formation template to autoscale the cluster(autoscale the vm instances backing the cluster)

**Comment by fijimunkii** [comment]
This helped me https://stelligent.com/2017/09/26/application-auto-scaling-with-amazon-ecs/
