### ISSUE TITLE
Unable to write response for cloudformation custom resource

### ISSUE THREAD

**Issue by nicklofaso** [awslabs/aws-cloudformation-templates#100]
I am trying to initialize an RDS instance using a lambda function triggered from a cloudformation custom resource. I am using the [python_custom_resource_helper](https://github.com/awslabs/aws-cloudformation-templates/tree/master/community/custom_resources/python_custom_resource_helper) from this repo (which has been great) to handle sending the response. 

The lambda function is called successfully and the database initializes without issue. However the lambda function seems unable to connect to s3 to write the response. I assume it is a permissions issue, but am not sure what I need to update. 

cloudwatch logs:
```
[16b5f688-cc49-4163-bb05-d961ba437ce9][2018-10-24 03:04:11,113][INFO] Completed successfully, sending response to cfn
[16b5f688-cc49-4163-bb05-d961ba437ce9][2018-10-24 03:04:12,170][ERROR] send(..) failed executing requests.put(..): HTTPSConnectionPool(host='cloudformation-custom-resource-response-useast1.s3.amazonaws.com', port=443): Max retries exceeded with url: /arn%3Aaws%3Acloudformation%3Aus-east-1%3A164513338535%3Astack/ltak2/86ac7dd0-d735-11e8-9b9e-503aca4a5835%7CrdsInitCustom%7C16b5f688-cc49-4163-bb05-d9
```
Lambda role has the following permissions
`AmazonS3FullAccess`
`AWSLambdaVPCAccessExecutionRole`

My user that kicks off cloudformation has `AdministratorAccess` and  `AmazonS3FullAccess` as well. 

Is there something else I need to configure for the response to write correctly?

**Comment by nicklofaso** [comment]
That sounds exactly like the problem, I will test it out shortly, thank you!

To reiterate I should setup a VPC endpoint to `com.amazonaws.us-east-1.s3` and then ensure the lambda has permissions to write to the s3 bucket `cloudformation-custom-resource-response-us-east-1` similar to this aws [article](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-vpce-bucketnames.html)

**Comment by Joel-fogue** [comment]
I'm stuck on the same issue as well, any success on this yet @nicklofaso ?

**Comment by cmmeyer** [comment]
Yup. Also make sure you place the lambda in a subnet with a route to the endpoint. :)
It's a different use case, but you can find a cheat on setting up the S3 endpoint as part of this larger blog on the CloudFormation endpoint:
https://aws.amazon.com/blogs/mt/signaling-aws-cloudformation-waitconditions-using-aws-privatelink/

The templates are in this repo: https://github.com/awslabs/aws-cloudformation-templates/tree/master/aws/solutions/CloudFormationEndpointSignals

**Comment by nicklofaso** [comment]
@Joel-fogue yes its working for me now. All I needed was a VPC Endpoint to S3. 

VPC -> Endpoint -> Create Endpoint
Choose `com.amazonaws.region.s3`
Choose your VPC
Choose the subnets where your Custom Resource will run

**Comment by Joel-fogue** [comment]
@cmmeyer @nicklofaso could you guys please help me figure out where I get the AdministratorARN and ExecutionRole from for the stackset stack?
