### ISSUE TITLE
Where do I get the AdministrationRoleARN and ExecutionRoleName ? `Lambda stack` deploys successfully but `stackset` creation fails

### ISSUE THREAD

**Issue by Joel-fogue** [awslabs/aws-cloudformation-templates#101]
I'm relatively new and learning AWS right now.  We have a requirement to provision resources across DEV and QA environments.

You have the following in _**stackset-function-template.yaml**_: 

```
Parameters:
  ModuleName:
    Type: String
    Default: "lambda_function"

  RoleName:
    Type: String
    Default: ""

  RolePath:
    Type: String
    Default: ""

```
1. It looks like step 1 is to deploy the function stack: 
When I deploy the function stack _**(stackset-function-template.yaml)**_, it deploys it successfully
1a. But where do I get the _**Rolename**_ and _**rolepath**_?_ 
It seems that if I don't wanna override those 2 parameters, they'll automatically be assigned during stack deployment

2. It then seems that step 2 is to issue a `stack create` command to create the stackset stack _**(stack-set-template.yaml)**_

But when I do that I get the following error below:

The following resource(s) failed to create: [StackSet]. . Rollback requested by user.
Where do I get the **_AdministrationRoleARN_** and **_ExecutionRoleName_**  and how do I pass them to the template?

```
  | 17:02:39 UTC-0400 | CREATE_FAILED | Custom::StackSet | StackSet | Failed to create resource. Parameter validation failed: Invalid length for parameter AdministrationRoleARN, value: 0, valid range: 20-inf Invalid length for parameter ExecutionRoleName, value: 0, valid range: 1-inf (See CloudWatch Log Stream: 2018/10/26/[$LATEST]3de21a37c64c35sdfa08e2194ecc22b5b)
  | 17:02:39 UTC-0400 | CREATE_IN_PROGRESS | Custom::StackSet | StackSet | Resource creation Initiated

```

Where do I get the _**AdministrationRoleARN**_ and **_ExecutionRoleName_** ?

**Comment by Joel-fogue** [comment]
Does it receive the `AdministrationRoleARN` and `ExecutionRoleName` from the `serviceToken`?

**Comment by Joel-fogue** [comment]
Should I be using this link to create both roles and pass them in? https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/stacksets-prereqs.html
I have no idea where to get those from and I really need help so I can implement a cross account deployment flow for work; really hope someone was able to go through this.
Should I maybe deploy the lambda in the `target account` but the actual stackset stack in the `administrator account`? I'm new to aws and learning as much as I can to piece this together

**Comment by LRomandine** [comment]
This is not an official support channel. Please use the AWS console and log a support ticket.

https://aws.amazon.com/premiumsupport/knowledge-center/information-support-case/

**Comment by cmmeyer** [comment]
Hey @Joel-fogue -- I wrote the original version of the custom resource.  Originally, StackSets required roles with specific names -- a recent PR addressed a StackSet change that allows you to use roles with arbitrary names, but doesn't pick up the default names.  I'll try to dig into it.

Either way you need to set up roles for the StackSet.  Here's more info on setting up the roles properly:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/stacksets-prereqs.html

**Comment by Joel-fogue** [comment]
@cmmeyer Thank you, I figured that out eventually; I can create a PR to include 2 additional templates: 

1st template for the administrator role in admin account
2nd template for the execution role in target accounts

In any case, thank you very much for your response!

**Comment by cmmeyer** [comment]
We'll also need a PR to make sure we default to the standard role names if one is not supplied -- I think the current default results in a blank role name :P
