### ISSUE TITLE
stack-set-template not aware of updates to the TestResources templates (events.yaml)!

### ISSUE THREAD

**Issue by Joel-fogue** [awslabs/aws-cloudformation-templates#104]
@cmmeyer Thank you for merging my PR but now I need some help please

I get the overall concept we're using custom resources to help us create our changeset with Cloudformation since cloudformation doesn't have that ability out of the box; which is the intended use of custom resources to fill in where cloudformation comes up short.

Now, when I make an update to the `TestResources/events.yaml` to add a `TableName` property to the dynamodb table in `events.yam`, I need to re-deploy the stack-set-template right? When I redeploy it fails to create a changeset because cloudformation doesn't see the updates I made to that `TestResources/events.yaml`

One solution would be to delete the stacks, modify my `TestResources/events.yaml` and start again from scratch by redeploying but if we're going to be provisioning resources in `qa` and `dev` overtime these resources will add up and if we need to go back and update one of our resources in the `TestResources/events.yaml`  let's say to include a new IAM role to some resource then the current solution doesn't seem to be able to detect those changes

_**So how do I make my stackset be aware of changes/updates made to the `TestResources/events.yaml` templates without deleting everything and redeploying?**_

The accompagnying video showed how to do updates by adding another account and region but what about updates to the actual resources that we're provisionning? 

It throws this error since it can't detect any changes from that `TemplateURL` properties under the stackset custom resource:

_**Failed to create the changeset: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: The submitted information didn't contain changes. Submit different information to create a change set.
Done**_

**Comment by cmmeyer** [comment]
Hey @Joel-fogue -- sorry for the delayed response.  I see your point -- no change to the properties mean CloudFormation doesn't see this as an update to the custom resource.  You could change the file name, but that's no good for versioning.

This comes up in other contexts were CloudFormation isn't aware of changes to the contents of files it relies on, like Lambda function code.  There's a PFR for a feature that would allow you to set a custom resource to always get triggered on update and I can document this as another use case.

In the meantime, a trick I've seen in other places is to add a "timestamp" property to the custom resource.  If we always increment this value, the custom resource will always trigger. 

Here's an example:
https://stackoverflow.com/questions/41452274/how-to-create-a-new-version-of-a-lambda-function-using-cloudformation

If you think it would work for you, I can work on a quick PR to add it.

**Comment by Joel-fogue** [comment]
@cmmeyer It's funny you mention the "timestamp" trick; I got around this issue by adding an additional tag called "**_ForceUpdateValue_**" to the `stackset-templates/stack-set-template.yaml` template like this: 

> AWSTemplateFormatVersion: '2010-09-09'
> Description: Let's build a StackSet
> Parameters:
>   StackSetName:
>     Type: String
>     Description: "[Optional] Unique name for this StackSet"
>  **_ForceUpdateValue:
>     Type: String
>     Default: 0
>     Description: This value allows me to force an update on the stackset since cloudformation doesn't seem to be able to detect changes to the TemplateURL templates_**
>    ....................
> 

Then I have a shell script that allows me to pass in that `ForceUpdateValue` parameter like this: 

> echo "Updating stackset template to stack in us-east-1"
> 
> aws cloudformation update-stack-set \
>  --stack-set-name my-stack-set \
>  --use-previous-template \
>  --parameters **_ParameterKey=forceUpdateValue,ParameterValue=1_** \
>  --operation-preferences FailureToleranceCount=0,MaxConcurrentCount=1 \
> --region us-east-1 \
> --profile default 

It seems similar to your suggestion, will review your suggestion, just wanted to share how I got around this issue although it still feels a bit `hacky` but gets the job done.

I'll be working with stackset for the next couple of weeks for my job and as I learn more, I'll help contribute back by submitting PRs where it makes sense; just haven't had much time due to the steep learning curve with AWS.

**Comment by cmmeyer** [comment]
Heya! Since we haven't chatted here in a while, I'm going to go ahead and close the issue.
