### ISSUE TITLE
Defect: aws/solutions/StackSetsResource/Templates/stackset-function-template.yaml: Function timeout set to 5 mins vs 15 mins

### ISSUE THREAD

**Issue by ckamps** [awslabs/aws-cloudformation-templates#118]
aws/solutions/StackSetsResource/Templates/stackset-function-template.yaml

I recently submitted a PR to this custom resource to take advantage of the recent enhancement the Lambda service to support 15 minute timeout vs the previous 5 minute timeout, but I neglected to update the `stackset-functiona-template.yml` file to increase from 300 seconds to 900 seconds.

As a workaround, you can modify the following line of code:

https://github.com/awslabs/aws-cloudformation-templates/blob/master/aws/solutions/StackSetsResource/Templates/stackset-function-template.yaml#L91

to specify:

```
      Timeout: 900
```

**Comment by cmmeyer** [comment]
Looks like this didn't get closed when I merged the PR. Closing now.
