### ISSUE TITLE
Iterator/Loop Macro to create multiple resources taking `count` as parameter?

### ISSUE THREAD

**Issue by Private-SO** [awslabs/aws-cloudformation-templates#133]
Hello,

I am looking for the `Iterator/Loop Macro` which you had explained in `AWS Reinvent:2018`. Can you please share it here ?

Thanks

**Comment by cmmeyer** [comment]
Weird. I thought all of the examples from the presentation were up here. Let me work on getting this added.

**Comment by cmmeyer** [comment]
Should be there now. It's the "Count" macro. Sorry about that!
