### ISSUE TITLE
Typo in readme

### ISSUE THREAD

**Issue by galenballew** [awslabs/aws-cloudformation-templates#146]
https://github.com/awslabs/aws-cloudformation-templates/tree/master/aws/services/CloudFormation/MacrosExamples/StringFunctions

Under **Basic Usage** it says that the input string is being converted to lowercase, but the Operation listed is Upper

**Comment by cmmeyer** [comment]
Thanks! Did a quick edit to get the text aligned to the example.
https://github.com/awslabs/aws-cloudformation-templates/commit/57f00616a54b511d2c5aa6e2e47f441997196a9e
