### ISSUE TITLE
Use of requestid as 'extra' seems to break logging for botocore, boto3, and pretty much every other logger

### ISSUE THREAD

**Issue by justchris1** [awslabs/aws-cloudformation-templates#157]
OK - I have been looking at this a while and I am not a python ninja.  However, I have come to an initial conclusion that the setting of log format in crhelper.py lines 46-48 breaks boto3, botocore, and other loggers:
`   # Set log message format`
`    logfmt = '[%(requestid)s][%(asctime)s][%(levelname)s] %(message)s \n'`
`    mainlogger.handlers[0].setFormatter(logging.Formatter(logfmt))`

Boto3 and botocore seem to catch the exception (which is of the general form:'requestid': KeyError Traceback) and just don't write anything out even when explicitly set.  Use of other modules which don't catch this exception seem to just die.  This seems to be due to the fact that the format string expects 'requestid' which is not a reserved attribute (one that is always set, see https://docs.python.org/2/library/logging.html#logrecord-attributes for a list).  The ability to set custom attributes seems to be here to let code define some data to present that is outside the always defined attributes, and can be done by passing a dict as an extra argument to the logging function (ex: logger.error('Something bad happened', extra={'requestid': 'SOMEIDNUM'}).  However, this requires every call to the logger to define that requestid field (or whatever you want to use in your code).  The documentation states that "While this might be annoying, this feature is intended for use in specialized circumstances, such as multi-threaded servers where the same code executes in many contexts, and interesting conditions which arise are dependent on this context".  

However, there is another helper function which does seem to be used in crhelper.py on line 49:
`return logging.LoggerAdapter(mainlogger, {'requestid': event['RequestId']})`
The LoggerAdapter (discussed https://docs.python.org/2/library/logging.html#loggeradapter-objects) pretty much emulates a logger object, but passes the extra dictionary every time without being asked.  It seems to make it easier to automatically include, but still hide the complexity of, the additional attribute.  You can pass a LoggerAdapter back to anything expecting to see a logger and all calls to that logger will include the extra parameter.  Here is where my python ninja definitely runs short:  it seems the author is 'handling' this by passing back the LoggerAdapter and in the README.md in handler() it seems they are trying to make it 'stick' by declaring logger global.  I am not sure this is having the intended effect.  Since other modules will likely be calling logging.getLogger(__name__) directly, they will not be passed the global LoggerAdapter version.  Even though many (all?) may indeed call it logger, since that logger is of more local scope in that module, the raw logger (not the LoggerAdapater) version will be used and thus it won't have the LoggerAdapter dictionary.  Perhaps I am missing something subtle here, or there is a simple fix.  However, the only one I can arrive at is removing requestid from the format string.  You can simply log the request id at the entry into 'handler'.  This is less functional as the visual sorting by eventid is nice, as each time update and delete are called they will have different ids and it is easy to see where the custom resource 'restarted' entry, but not crashing is generally more desirable.  But, perhaps I am missing something simple.

**Comment by mleziva** [comment]
This implementation has been deprecated in favor of https://github.com/aws-cloudformation/custom-resource-helper which has a richer feature set, is cleaner to implement and can be installed as a pip module.
