### ISSUE TITLE
Possible typo in crhelper.py:log_config

### ISSUE THREAD

**Issue by justchris1** [awslabs/aws-cloudformation-templates#158]
I am pretty sure that line 34 in crhelper.py has a minor typo in it.  The line reads:

`loglevel = event['ResourceProperties']['botolevel']`
when I think it should instead read:
`botolevel = event['ResourceProperties']['botolevel']`

This means that even if botolevel is defined as an input to the custom resource, the boto level of debug (botocore and boto3) will not be affected.  Only a direct invocation of log_level with the parameter of botolevel='SETTING' will set it to the desired level.  However, issue #157 seems to stop the actual boto debug from making it into the logs.

**Comment by mleziva** [comment]
This implementation has been deprecated in favor of https://github.com/aws-cloudformation/custom-resource-helper which has a richer feature set, is cleaner to implement and can be installed as a pip module.
