### ISSUE TITLE
Setting an "M out of N" cloudwatch alarm in Cloudformation Template

### ISSUE THREAD

**Issue by ghost** [awslabs/aws-cloudformation-templates#160]
So an "M out of N" alarm could be like if 3/5 datapoints are above the threshhold for X consecutive periods, the alarm is raised.

I get that M is for Datapoints to Alarm, and N is for EvaluationPeriods.

` EvaluationPeriods: "4"
   DatapointsToAlarm: "5"
   Threshold: "15"`

I have 5 Data points set, but I only want it so if atleast 3 are above the threshold for 4 periods, an alarm is released. How would I specify in a CFT yaml file that I want 3/5 datapoints?

**Comment by navid-taheri** [comment]
Answered: https://stackoverflow.com/questions/50262776/how-to-enable-m-out-of-n-cloudwatch-alarm-with-cloudformation
