### ISSUE TITLE
S3 website endpoints inconsistent with docs

### ISSUE THREAD

**Issue by mhuebert** [awslabs/aws-cloudformation-templates#161]
Hello,

A colleague reported problems using the S3 website suffix for `us-east-2` that had been copied from a template in this repo. I looked into it and see that some of the endpoints in [S3_Website_With_CloudFront_Distribution.yaml](https://github.com/awslabs/aws-cloudformation-templates/blob/master/aws/services/S3/S3_Website_With_CloudFront_Distribution.yaml#L16) do not match those listed in the [AWS documentation](https://docs.aws.amazon.com/general/latest/gr/rande.html#s3_website_region_endpoints).

For example, the suffix for `us-east-2`:
```
.s3-website-us-east-2.amazonaws.com   // this repo
 s3-website.us-east-2.amazonaws.com   // general docs
```
These are subtle differences (`-` vs `.`) which vary between regions, not appearing to follow any consistent rule.

Can someone confirm which source should be taken as correct, and if this repo should be updated?

**Comment by yashshanker** [comment]
Hi @mhuebert , thanks for bringing this issue in notice.

I've raised a PR(#165) for the same.
