### ISSUE TITLE
Support for athena DB/Table resource creation

### ISSUE THREAD

**Issue by vish91** [awslabs/aws-cloudformation-templates#173]
Are there any plans for supporting AWS Athena operations via cloudformation ? 
From docs, it seems to only support creating named resources https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-reference-athena.html

**Comment by mleziva** [comment]
Now supported: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_Athena.html
