### ISSUE TITLE
DelaySeconds Parameter Description wrong?

### ISSUE THREAD

**Issue by pyrokin5** [awslabs/aws-cloudformation-templates#249]
https://github.com/awslabs/aws-cloudformation-templates/blob/2249cbe7760f7c7bd4adbae5301d0c4ace8a037d/aws/services/SQS/SQSFIFOQueue.json#L18-L19

**Comment by NickMinnellaCS** [comment]
[DelaySeconds](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sqs-queues.html): 
The time in seconds for which the delivery of all messages in the queue is delayed. You can specify an integer value of 0 to 900 (15 minutes). The default value is 0.
