### ISSUE TITLE
Enable to configure copying tags of Neptune DB instances to snapshots

### ISSUE THREAD

**Issue by jindrichmynarz** [awslabs/aws-cloudformation-templates#280]
CloudFormation currently cannot configure copying tags of [Neptune DB instances](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-neptune-dbinstance.html) to their snapshots. This can be done via the AWS CLI's option `--copy-tags-to-snapshot` for [`aws neptune modify-db-instance`](https://docs.aws.amazon.com/cli/latest/reference/neptune/modify-db-instance.html). Can you enable it for CloudFormation too?

**Comment by uadev** [comment]
copy_tags_to_snapshot parameter is a part of RDS, but unfortunately, this is not supported for Neptune (

**Comment by jindrichmynarz** [comment]
This is now supported by CloudFormation via [`CopyTagsToSnapshots`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-neptune-dbcluster.html#cfn-neptune-dbcluster-copytagstosnapshot).
