### ISSUE TITLE
AWS Lambda end of support for Python 2.7 - S3Objects

### ISSUE THREAD

**Issue by dmarinuswoodwing** [awslabs/aws-cloudformation-templates#300]
We got a notification that AWS Lambda end of support for Python 2.7

S3Objects still uses Python 2.7:
https://github.com/awslabs/aws-cloudformation-templates/blob/bbcd9de803c7fe7c27063812b522bc900463b1d7/aws/services/CloudFormation/MacrosExamples/S3Objects/macro.template#L7

This requires some work to get this working with Python 3:
```
$ python3 lambda/resource.py 
Traceback (most recent call last):
  File "S3Objects/lambda/resource.py", line 14, in <module>
    from urllib2 import build_opener, HTTPHandler, Request
ModuleNotFoundError: No module named 'urllib2'
```

**Comment by stilvoid** [comment]
Fixed in #301
