### ISSUE TITLE
CREATE_COMPLETE state and cannot be signaled

### ISSUE THREAD

**Issue by premgurung** [awslabs/aws-cloudformation-templates#34]
Hi Team 
Please help me to resolve the below ValidationError
+ /opt/aws/bin/cfn-signal -e 0 --stack RedHat7Cfn --resource EC2Instance --region us-east-1
ValidationError: Stack arn:aws:cloudformation:us-east-1:861450004289:stack/RedHat7Cfn/7d2e3dd0-f5f3-11e7-93f5-50a686e4bb4a is in CREATE_COMPLETE state and cannot be signaledhanks

Thanks
Prem

**Comment by LRomandine** [comment]
Which template from this repo are you using and have you modified the template before running it?

**Comment by premgurung** [comment]
we are using RHEL7_cfn-hup.template from the repo and we have not modified any template before running .

Thanks
Prem

**Comment by LRomandine** [comment]
Where are you seeing the error?  I ran the template multiple times in my account in the us-east-1 region and checked /var/log/messages and /var/log/cloud-init.log my cfn-signal does not error.  

The only way I can reproduce your error is if I manually run the cfn-signal command myself after bootstrapping is complete, but I would expect that to cause that error.

**Comment by premgurung** [comment]
thanks for the update

**Comment by santhosh34** [comment]
I got this error when i manually terminated Ec2 and expected one more instance to match minimum count.
