### ISSUE TITLE
Any sample for AWS PrivateLink

### ISSUE THREAD

**Issue by melih154** [awslabs/aws-cloudformation-templates#35]
As mentioned [here](https://aws.amazon.com/about-aws/whats-new/2017/11/introducing-aws-privatelink-for-aws-services/) and can be accessible from [here ](https://eu-west-2.console.aws.amazon.com/vpc/home?#Endpoints:)

Couldn't find any sample CloudFormation template on VPC Endpoint for Endpoint Type **Interface**.

**Comment by LRomandine** [comment]
Documentation (including an example) can be found in the AWS CloudFormation documentation here.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcendpoint.html

**Comment by melih154** [comment]
@LRomandine Thanks for quick response. This doesn't cover the VPC Endpoint - Type Interface Eg. SSM. 

Need to be able to set SubnetIds and SecurityGroupId - as can be done via UI - none of the properties on CloudFormation covers that.  Please check [this screenshot](https://imgur.com/a/HEVDi).

**Comment by LRomandine** [comment]
Ah, I misunderstood which endpoint you were referring to, sorry about that.

I do not believe CloudFormation support for those endpoints is implemented yet.  You can log a support ticket via the console as a feature request, this helps the CloudFormation team prioritize their roadmap.
