### ISSUE TITLE
Template for AWS Sagemaker

### ISSUE THREAD

**Issue by ponnou** [awslabs/aws-cloudformation-templates#43]
Hello,

I am trying to generate a template which can instantiate an AWS Sagemaker via CloudFormation, do you have any simple example (to start) ?   

Thank you,
Andre

**Comment by LRomandine** [comment]
AWS Sagemaker is not supported in CloudFormation yet.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-template-resource-type-ref.html
