### ISSUE TITLE
AWS CloudFormation new Stack status

### ISSUE THREAD

**Issue by ansariwn** [awslabs/aws-cloudformation-templates#73]
We use AWS Cloudformation stack to provision resources. I have noticed that when we create a new stack using our cloudformation template the final status of our stack is Update_Complete instead of Create_Complete. This is causing our monitoring scripts to fail because the final status of stack is Update_Complete and not Create_Complete. Can anyone help to find out why the final status of a newly created stack be Update_Complete?

Our Cloudformation template provisions an EC2instance and then executes some UserData commands. We make use of WaitCondition to wait for the EC2instance to become available. Any idea what could be the issue here?

**Comment by LRomandine** [comment]
This is not an official support channel.  Please use the AWS console and log a support ticket.

https://aws.amazon.com/premiumsupport/knowledge-center/information-support-case/
