### ISSUE TITLE
Possible dependency issue in ECS VPC template

### ISSUE THREAD

**Issue by simonk52** [awslabs/aws-cloudformation-templates#75]
Hi,

I've been using the `aws/services/ECS/FargateLaunchType/clusters/private-vpc.yml` template to create a VPC. On one instantiation I received this error message for the PublicLoadBalancer resource:

> VPC vpc-01bc156233b79a0b6 has no internet gateway (Service: AmazonElasticLoadBalancingV2; Status Code: 400; Error Code: InvalidSubnet; Request ID: ef47ee8e-af60-11e8-a6e2-2da24784aabf)

According to https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-dependson.html#gatewayattachment, load balancers need a `DependsOn` entry for the internet gateway. Does that need to be added here?

Thanks :-)

Simon

**Comment by LRomandine** [comment]
You are correct.  This is a race condition, sometimes the attachment happens early enough where it will not error, sometimes it won't.

Fixed.
https://github.com/awslabs/aws-cloudformation-templates/commit/6e3af420c3a872adf3b89db3a5a36ac994d676ff
