### ISSUE TITLE
Incorrect link in ECS README

### ISSUE THREAD

**Issue by simonk52** [awslabs/aws-cloudformation-templates#76]
Hi,

The [Publicly Exposed Service with Private Networking](https://github.com/awslabs/aws-cloudformation-templates/blob/master/aws/services/ECS/README.md#publicly-exposed-service-with-private-networking) section of the ECS sample includes this:

```
### Run in AWS Fargate

1. Launch the [public + private](FargateLaunchType/clusters/private-vpc.yml) cluster template
2. Launch the [public facing service template](FargateLaunchType/services/public-service.yml).
```

I think the second link should point to the `private-subnet-public-service.yml` template instead. I followed the instructions literally and it took me a while to notice that my containers were running in the public subnet rather than the private one.

Thanks :-)

**Comment by LRomandine** [comment]
You are correct.

Fixed . https://github.com/awslabs/aws-cloudformation-templates/commit/4e5f71f1510e30c2c71a6141c64299871851832d

In the future, feel free to fork the repo, fix it, and submit a PR.
