### ISSUE TITLE
Many issues listed here are caused by a lack of proper software packaging

### ISSUE THREAD

**Issue by michael-crawford** [awslabs/aws-cloudformation-templates#87]
I found this project via Google search, again feeling very frustrated that I, and those who appear to be on similar quests, are again wasting HOURS if not DAYS of our time because AWS software teams do not properly package their software into RPMs, DEBs and MSIs. 

There should be no need for these workarounds, period. 

Imagine if every time you wanted to use tomcat, you had to write your own init.d script or systemd script, or were given only an init.d script on RHEL 7 which didn't work because it uses systemd. Then, compound that with NO examples, NO documentation on how to get things to work.

I have literally lost over TWO WHOLE MONTHS of my time in the last 3 years having to deal with problems related to a lack of proper software packaging which has been standard in the industry for RHEL/CentOS and Ubuntu distributions for well over 10, maybe 20 years. This lack of proper packaging is something I'd find a bit "non-professional" for a startup with 10 people. To see this coming out of AWS, the largest/best (other than in this area) cloud provider, with thousands of engineers, is just flat out shocking.

Today, my problem is attempting to get cfn-hup to work properly in Ubuntu. Yeah, I know - pretty obscure. THE way AWS advertises as the way to install software inside CloudFormation. THE way AWS creates all their QuickStarts to show how complex applications can be automated. An OS that no one uses any more. I guess everyone has switched to Teraform. ... W. T. F.?

The cfn-init services section doesn't support systemd. It still uses initv,  Install the new amazon-cloudwatch-agent and try to setup a services section which restarts when a stack update changes the config file - good luck. The idiots who "packaged" the deb file never bothered to test that this worked in CloudFormation. It doesn't, thows errors. That's because Ubuntu has not used init scripts in what - 5 to 7 years - I've lost count. 

Is it really too much to ask that AWS software delivers the few key packages we use to integrate with and automate AWS in the form of packages that EVERY. SINGLE. OTHER. MAJOR. SOFTWARE. VENDOR. uses to deliver their stuff?

I have opened over a dozen tickets, asking for this. Wasted weeks of time figuring out workarounds. You can see many, many google posts for people who have similarly lost time because this has not been done properly. What is it going to take for AWS management to stop, take a FUCKING WEEK OR TWO - seriously that's all the effort required to package this stuff right, I've done it myself many times, and stop this madness!

Forgive me for venting. I'm just fed up that this festering problem just does not get fixed.

Please do talk to whoever works for you that packaged SSM Agent. Promote that guy and ask him to help the other teams do this right. This is not rocket science. Thousands of open source projects do this every day. You would save me, as well as what I can tell are hundreds of other people, based on my research looking for solutions and seeing the pain out there, hundreds of hours of wasted time.

it is the correct way to do this. It is the right way to treat your customers. It is not hard to do this. Thousands of other open source projects do this. You can do this. Please do this!

What I want:
- Create and RPM, DEB, MSI, for
- awscli, amazon-ssm-agent (mostly there), amazon-cloudwatch-agent (PATHETIC!!!!!!!!!), cfn-init (PATHETIC!!!!!).
- keep these CURRENT, Jesus! Publish a new rpm/deb/msi when you publish the tar.gz, like everyone else does.
- Put the binaries, conf, data files in the correct, SAME locations on each Linux OS, following the LFHS convention. It is the standard!

Every other open source project does this. Why can't you? You're a $1T company.

That is all.

**Comment by cmmeyer** [comment]
Thank you Michael.
 
I've forwarded the CloudWatch teams for your comments regarding their agent. 
 We've also reminded AWS CLI of the open https://github.com/aws/aws-cli/issues/2501 issue and I've passed on the positive feedback to the SSM team, including the promotion suggestion :)

For the CloudFormation helpers scripts, we've been talking a lot internally lately about how to modernize them and keep them fresh.  Would you be willing to chat with me further about it?  You can reach out to me via email (cmmeyer@amazon.com) or twitter (chuckm@).

**Comment by cmmeyer** [comment]
I've captured Michael's concerns and there are internal discussions around the points mentioned above.  I'm closing this issue since there's really nothing that's going to be actionable via CloudFormation templates.
