### ISSUE TITLE
CloudFormation ShortHand Macro - future resource type ambiguity

### ISSUE THREAD

**Issue by PatMyron** [awslabs/aws-cloudformation-templates#89]
@stilvoid 

https://github.com/awslabs/aws-cloudformation-templates/blob/dafa8f270d5047e97722dd0b0d49995a8ea90396/aws/services/CloudFormation/MacrosExamples/ShortHand/README.md

I'm not sure it's a good idea to encourage customers to omit the AWS Service prefix.

When a new resource type is launched that introduces new ambiguity, all of those CloudFormation templates creating the previously unambiguous resource type this way would be broken overnight.

**Comment by stilvoid** [comment]
Hi Pat, thanks for the comment. You're correct in principle, however the list of resource types that the macro uses to disambiguate ShortHand names is stored [with the macro code](https://github.com/awslabs/aws-cloudformation-templates/blob/dafa8f270d5047e97722dd0b0d49995a8ea90396/aws/services/CloudFormation/MacrosExamples/ShortHand/lambda/spec.json) (This is actually a copy of the CloudFormation spec) so you would need to consciously update this file and update the macro's lambda function in your account before this can happen so it would have to be a conscious decision.
