### ISSUE TITLE
cant connect to rds

### ISSUE THREAD

**Issue by josersleal** [awslabs/aws-cloudformation-templates#91]
connection to bastion via ssh works
connection to rds does not work because connection is redirected to the bastion...

quote: "Using a security group ID as a source only works when the traffic is addressed to the private IP. By trying to hit the public IP the traffic is being routed outside the VPC and back in to the VPC, at which point the source security group information has been lost. "

running the command inside bastion at public bastion ip:
mysql -h rds-cluster-endpoint -P 3306 -u startupadmin -p
Enter password:

generates error:
ERROR 1045 (28000): Access denied for user 'startupadmin'@'bastion private ip' (using password: YES)

**Comment by cmmeyer** [comment]
Thanks for the feedback -- which template where you using to deploy this architecture?

**Comment by josersleal** [comment]
Sorry for the delay.

Ignore this...

In the end the error was correct and I was using a wrong set of user-pass combination.
