### ISSUE TITLE
c# port of customresourcehelper .

### ISSUE THREAD

**Issue by turjachaudhuri** [awslabs/aws-cloudformation-templates#92]
Hi , the custom resource helper that helps with handling custom resources is written in python and can be found at - aws-cloudformation-templates/community/custom_resources/python_custom_resource_helper/

Any idea/release plan for a c# version of this?

**Comment by jaymccon** [comment]
Thanks for reaching out @turjachaudhuri , I wrote the python  helper, but don't have the skills to do a c# port 😞 

It would be great to see this in other runtimes, most of the logic should be pretty universal. Any volunteers ?

**Comment by mleziva** [comment]
This resource is no longer managed in this repository. The new repository for the custom-resource-helper: https://github.com/aws-cloudformation/custom-resource-helper

If this functionality is still required, please open an issue in the new repository.
